services:
    app:
        build:
            context: .
            target: dev
        container_name: proassist-api-dev
        volumes:
            - .:/var/www/html:rw
        environment:
            APP_ENV: dev
            APP_SECRET: local_dev_secret_key
            DATABASE_URL: "postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8"
        depends_on:
            database:
                condition: service_healthy

    nginx:
        image: nginx:alpine
        container_name: proassist-nginx-dev
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

    database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        container_name: proassist-db-dev
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
            timeout: 5s
            retries: 5
            start_period: 10s
        ports:
            - "5432:5432"
        volumes:
            - database_data:/var/lib/postgresql/data:rw

    messenger-worker:
        build:
            context: .
            target: dev
        container_name: proassist-worker-dev
        command: php bin/console messenger:consume async -vv --limit=50
        restart: unless-stopped
        volumes:
            - .:/var/www/html:rw
        environment:
            APP_ENV: dev
            APP_SECRET: local_dev_secret_key
            DATABASE_URL: "postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8"
        depends_on:
            database:
                condition: service_healthy

volumes:
    database_data:
